### ISSUE TITLE
Significant number of uplink packets are not being transmitted

### ISSUE THREAD

**Issue by CanEmreUnal** [helium/helium-packet-router#308]
We are experiencing a noticeable decrease in packet arrivals to our ChirpStack LNS over the last three days. Specifically, the packet reception rate has dropped by approximately 1/3 compared to previous levels.

Here is the current configuration for reference:

```
{
  "org": {
    "oui": 26,
    "owner": "XXXX",
    "payer": "XXXXX",
    "delegate_keys": [
      "XXXX"
    ],
    "locked": false
  },
  "net_id": "XXXX",
  "devaddr_constraints": [
    {
      "start_addr": "XXXX",
      "end_addr": "XXXX"
    }
  ]
}
```
I @macpie redacted this

**Comment by macpie** [comment]
Could you provide your `ROUTE ID` ?

**Comment by CanEmreUnal** [comment]
ae92ae20-8872-11ee-90ee-5369153d8ed3

**Comment by macpie** [comment]
Checking

**Comment by macpie** [comment]
I think it should be fixed now, for some reason the Config Service did not provide your `devaddr_range` ...

**Comment by CanEmreUnal** [comment]
Is it something that should take time ?
Unfortunately, I didn't notice any progress yet.

**Comment by macpie** [comment]
I should be immediate, but your devices will need to transmit of course.

**Comment by CanEmreUnal** [comment]
We are certain that the devices with DevEUI 0016C001F0007036 and
0016C001F0007010 are transmitting. (we're seeing in packet-forwarder logs)

These represent just a small portion of the devices, but we are still not
receiving uplinks from them.

Could you please check on your end? Could it possibly be caused by waf
blocking?

**Comment by macpie** [comment]
I just ran an update on all the server and I can confirm that your route is everywhere now (just in case the hotspot transmitting your device's data was routed threw another server than one in the EU).

If data is still not showing up soonish, I can try to track your data:

1. Uplink via devaddr.
2. Joins via dev EUI ( DO NOT POST your APP EUI).
3. Or via a hotspot name that the device usually goes threw.

**Comment by CanEmreUnal** [comment]
It seems like they are gradually coming back online. Thank you for your efforts.
However, we are still wondering about the root cause and whether this issue might recur in the future.

**Comment by macpie** [comment]
This is most likely a disconnect between HPR and Config Service (that holds all the routing infos). I have seen this happen once or twice. 

I will keep this open and try to see if we can at least add metrics around this specific issue (missing devaddr range in route) and see if we can fix this by retrying in case we don't get one (range).

Note that this is an infrequent hedge case but nonetheless annoying and that should be fixed.

**Comment by pangguanyu** [comment]
We are facing similar issue now. Could you please take a look? Uplink log confirmed successfully to router on Gateway, but not sent to chirpstack. @macpie

**Comment by macpie** [comment]
> We are facing similar issue now. Could you please take a look? Uplink log confirmed successfully to router on Gateway, but not sent to chirpstack.BTW, we have 2 sensors. We are testing them together. 1 is sending data every 20s, another one is sending every 5minutes/30minutes. If we keep the 20s sensor online, everything looks good. But if we stop sending data from it, the sensor sending data every 5min/30min will have data loss. @macpie

How do you stop the 1st device from sending? It sounds like to me that when you disable that device you also disable the 2nd one.

FYI: I cannot debug anything from a LNS' device ID. Please see https://github.com/helium/helium-packet-router/issues/308#issuecomment-2557710060

**Comment by macpie** [comment]
- I have reconciled this route `ae92ae20-8872-11ee-90ee-5369153d8ed3` to every HPR in the fleet (if everything wasn't in sync before, it is now).
 - I also could not find any trace of DevEUI `0016C001F00076D5` but found  `16C001F00076D5 ` (aka ~~00~~16C001F00076D5) maybe the issue is there?

**Comment by CanEmreUnal** [comment]
It seems to be working fine now — thank you, @macpie.

However, I'm still concerned that this issue has occurred again. I believe it's important to find a permanent solution to prevent this behavior in the future.

Do you have any plans to address this issue?

**Comment by macpie** [comment]
> Hi [@macpie](https://github.com/macpie) ,
> 
> Route ae92ae20-8872-11ee-90ee-5369153d8ed3 seems to be out of sync again. could you please check if the route is fully synced across HPRs?
> 
> We’re experiencing this issue more frequently now, and we’d like to understand how we can address or prevent it going forward.

I have fixed it. This is weird because you are the only one reporting this periodically. Could there be something on your side that devaddr range or that would play with config API?
